// Simple, beginner-friendly Node.js Express API Server
// Connects to MySQL Database and exposes note CRUD endpoints

const express = require('express');
const mysql = require('mysql2/promise');
const cors = require('cors');
require('dotenv').config();

const app = express();
const PORT = process.env.PORT || 5000;

// Enable CORS so the React frontend (port 3000) can talk to this backend (port 5000)
app.use(cors());

// Parse incoming JSON request bodies
app.use(express.json());

// MySQL Database Connection Pool
// A connection pool manages multiple database connections efficiently.
let pool;

const connectDatabase = () => {
  try {
    pool = mysql.createPool({
      host: process.env.DB_HOST || 'localhost',
      port: process.env.DB_PORT || 3306,
      user: process.env.DB_USER || 'root',
      password: process.env.DB_PASSWORD || 'your_mysql_root_password',
      database: process.env.DB_NAME || 'cozy_notes_db',
      waitForConnections: true,
      connectionLimit: 10,
      queueLimit: 0
    });
    console.log('🐬 MySQL Connection Pool initialized successfully.');
  } catch (error) {
    console.error('❌ Failed to initialize MySQL Pool:', error.message);
  }
};

connectDatabase();

// 1. GET ALL NOTES
// Fetches all note entries from the MySQL database, sorted from newest to oldest.
app.get('/api/notes', async (req, res) => {
  try {
    const [rows] = await pool.query('SELECT * FROM notes ORDER BY created_at DESC');
    res.json(rows);
  } catch (error) {
    console.error('Error fetching notes:', error.message);
    res.status(500).json({ 
      error: 'Failed to fetch notes. Make sure MySQL Server is running and your credentials in .env are correct!' 
    });
  }
});

// 2. CREATE A NEW NOTE
// Inserts a new note title and content row into the MySQL database.
app.post('/api/notes', async (req, res) => {
  const { title, content } = req.body;
  
  if (!title) {
    return res.status(400).json({ error: 'Title is required!' });
  }

  try {
    const [result] = await pool.query(
      'INSERT INTO notes (title, content) VALUES (?, ?)',
      [title, content || '']
    );
    
    // Send back the created note including the new ID auto-generated by MySQL
    res.status(201).json({
      id: result.insertId,
      title,
      content,
      created_at: new Date()
    });
  } catch (error) {
    console.error('Error creating note:', error.message);
    res.status(500).json({ error: 'Failed to save note to the database.' });
  }
});

// 3. DELETE A NOTE
// Removes a note from the MySQL database matching the ID parameter.
app.delete('/api/notes/:id', async (req, res) => {
  const { id } = req.params;

  try {
    const [result] = await pool.query('DELETE FROM notes WHERE id = ?', [id]);
    
    if (result.affectedRows === 0) {
      return res.status(404).json({ error: 'Note not found!' });
    }
    
    res.json({ message: 'Note deleted successfully!' });
  } catch (error) {
    console.error('Error deleting note:', error.message);
    res.status(500).json({ error: 'Failed to delete note from the database.' });
  }
});

// Start Express Server
app.listen(PORT, () => {
  console.log(`🚀 Server is running on http://localhost:${PORT}`);
  console.log('💡 Remember to setup cozy_notes_db in MySQL Workbench first!');
});
